### ISSUE TITLE
Transparent --background-color not layered correctly

### ISSUE THREAD

**Issue by FrostKiwi** [georgealways/lil-gui#109]
Enabling a transparent color via...
```css
.lil-gui {
	--background-color: #1f1f1fCC;
}
```
...causes the layered transparency to emerge. See Video below.
Folders introduce an additional layer of transparent color, which leads to the transparent color being overlayed and getting darker. Additionally, you can see a brighter line of padding "plopping into existence" when expanding a folder, though it won't be visible if the background transparency is handled correctly.

https://github.com/georgealways/lil-gui/assets/60887273/56414b98-9379-440a-9278-cdd2742a27a9

**Comment by georgealways** [comment]
Hi there—makes sense. I think it should probably work the way you want by default, but for now you could achieve that with something like this:

```css
.lil-gui { 
  --background-color: rgba(0,0,200,0.5);
}

.lil-gui:not(.root) { 
  background-color: transparent !important;
}
```

**Comment by FrostKiwi** [comment]
> but for now you could achieve that with something like this

Can confirm this fix working for transparency, but applying filters still causes artifacts due to the same reason I guess.

<details><summary>CSS</summary>

```css
.lil-gui {
	--widget-color: #2d3741;
	--background-color: #1f1f1f00;
	backdrop-filter: blur(calc(1vw + 1vh));
}
/* Fix as per: 
   https: //github.com/georgealways/lil-gui/issues/109#issuecomment-1611658861
 */
.lil-gui:not(.root) {
	background-color: transparent !important;
}
```

</details>

![image](https://github.com/georgealways/lil-gui/assets/60887273/453d6a75-e99a-4fa6-8666-b11de3acb254)


Just the effects is fine, but without tinting, it's unreadable.
<details><summary>CSS</summary>

```css
.lil-gui {
	--widget-color: #2d3741;
	--background-color: #1f1f1f00;
	backdrop-filter: blur(calc(1vw + 1vh));
}
/* Fix as per: 
   https: //github.com/georgealways/lil-gui/issues/109#issuecomment-1611658861
 */
.lil-gui:not(.root) {
	background-color: transparent !important;
}
```

</details>

![image](https://github.com/georgealways/lil-gui/assets/60887273/64f59a67-f02a-45ca-aca8-4dc0278ba8c0)

**Comment by georgealways** [comment]
Both the root GUI and folders have the `.lil-gui` class, so any effects that rely on transparency should only be applied to `.lil-gui.root`.

In a future release, `--background-color` will only be applied to the root GUI.

**Comment by FrostKiwi** [comment]
Can confirm...
```css
.lil-gui.root {
	--background-color: blur(calc(1vw + 1vh));
	backdrop-filter: #00000070;
}
/* Fix as per: 
   https: //github.com/georgealways/lil-gui/issues/109#issuecomment-1611658861
 */
.lil-gui:not(.root) {
	background-color: transparent;
}
```
...working flawlessly. The `!important` btw wasn't required...

**Comment by FrostKiwi** [comment]
Here is the finished product:
https://mirrorball.frost.kiwi/
I think the menu blur works really well with lil-gui!

Credit this package and your authorship in the repo: https://github.com/FrostKiwi/Mirrorball

**Comment by georgealways** [comment]
As of 0.19.0 you can specify a non-opaque `--background-color` without overriding internal css, and transparency won't stack.

**Comment by FrostKiwi** [comment]
Updated to 0.19.0 in my WebApp.
The little hack in [this line](https://github.com/FrostKiwi/Mirrorball/blob/508b123ea30ea91aa0855a8537508f5cb942e668/src/style/gui.css#L14) isn't needed anymore.
```css
/* Fix as per: 
   https: //github.com/georgealways/lil-gui/issues/109#issuecomment-1611658861
 */
.lil-gui:not(.root) {
	background-color: transparent;
}
```
However, Firefox and Chrome / Edge behave differently.
With
```css
.lil-gui {
	--widget-color: #2d3741;
	--background-color: var(--bgcolor);
	backdrop-filter: var(--blur);
	-webkit-backdrop-filter: var(--blur);
}
```
![image](https://github.com/georgealways/lil-gui/assets/60887273/303cbbc8-4e07-443b-913c-11d8ee925c28)
I still have to specify that `.root` to get all to behave the same. Otherwise on Firefox the transparencies stack again and there is that gap between last item of menu and next menu header again.
```css
.lil-gui {
	--widget-color: #2d3741;
}

.lil-gui.root {
	--background-color: var(--bgcolor);
	backdrop-filter: var(--blur);
	-webkit-backdrop-filter: var(--blur);
}
```
![image](https://github.com/georgealways/lil-gui/assets/60887273/f16110ad-b959-44cc-b667-bae79da0bb12)

PS: What would I have to style to get just the menu headers a bit darker like hover does? I would love to have it a touch darker, but not as dark as the hover color.
![image](https://github.com/georgealways/lil-gui/assets/60887273/c6429904-1ed7-455b-a957-76bc24def1d6)
