### ISSUE TITLE
--folder-title-color

### ISSUE THREAD

**Issue by georgealways** [georgealways/lil-gui#2]
@WestLangley Hey! So I was thinking more about the idea for this CSS var and I forgot you can do the following: 

```css
.lil-gui .title { 
  color: #fff;
}
```

Does that accommodate the use case you have in mind?
